services:
  sftp:
    build:
      context: ./image
      network: host
    network_mode: host
    volumes:
      - ./secret/id_ed25519:/etc/ssh/id_ed25519
      - ./secret/id_rsa:/etc/ssh/id_rsa
      - ./config/users.conf:/etc/sftp/users.conf:ro
      - ./share:/home