services:
  sftp:
    build:
      context: ./image
      network: host
    ports:
      - 2222:22
    volumes:
      - ./secret/id_ed25519:/etc/ssh/id_ed25519:Z
      - ./secret/id_rsa:/etc/ssh/id_rsa:Z
      - ./config/users.conf:/etc/sftp/users.conf:ro